### ISSUE TITLE
Домашнее задание по 4 лекции Db Level Up

### ISSUE THREAD

**Issue by MaxGaranin** [MaxGaranin/DanceSchool#31]
Подзадачи:
- [x] #27 Адаптировать доменные модели для работы со связанными сущностями
- [x] #28 Реализовать миграции
- [x] #29 После миграций в readme добавить получившуюся ERD
- [x] #30 Добавить UoW в приложение, адаптировать архитектуру под работу с ним
