### ISSUE TITLE
Домашнее задание по 5 лекции Security

### ISSUE THREAD

**Issue by MaxGaranin** [MaxGaranin/DanceSchool#36]
Подзадачи:
- [x] #37 Устранить уязвимости в своем проекте с API. В readme указать, что было устранено и как.
- [x] #38 Выбрать 1 уязвимость из лекции или из списков в сайтах OWASP и Semmle.
- [x] #39 Оформить следующий проект (отдельный реп, не в API): 1 файл – кусок кода, содержащий выбранную уязвимость, 2 файл – кусок кода, где уязвимость устранена неправильно, 3й файл – пример правильного устранения уязвимости. В Readme описать, что это за уязвимость, как ее можно атаковать, почему решение во 2 файле – неверное и почему верное в 3м. Всего 5-15 предложений.
