### ISSUE TITLE
Домашнее задание по 6 лекции Authentification

### ISSUE THREAD

**Issue by MaxGaranin** [MaxGaranin/DanceSchool#45]
- [ ] #41 К текущему API добавить аутентификацию и авторизацию (не забыть про новые сущности юзеров и ролей, миграции)  
- [ ] #42 Настроить CORS («белый» список, методы и т.д.)  
- [x] #43 Поставить докер к следующей лекции
- [ ] #44 В качестве факультатива: попробовать реализовать регистрацию и хранение в БД хешированных паролей
